DROP TABLE IF EXISTS params;

DROP TABLE IF EXISTS user_roles;

DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS media;

DROP TABLE IF EXISTS path_segments;

DROP TABLE IF EXISTS pathes;

DROP TABLE IF EXISTS segments_video_contexts;

DROP TABLE IF EXISTS video;

DROP TABLE IF EXISTS segments;


